[[redirects]]
  from = "/log-in"
  to = "https://dispatchitt.onrender.com/log-in"
  status = 200

[[redirects]]
  from = "/logged-in"
  to = "https://dispatchitt.onrender.com/logged-in"
  status = 200

[[redirects]]
  from = "/users"
  to = "https://dispatchitt.onrender.com/users"
  status = 200

  [[redirects]]
  from = "/parcels"
  to = "https://dispatchitt.onrender.com/parcels"
  status = 200

[[redirects]]
  from = "/logout"
  to = "https://dispatchitt.onrender.com/logout"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200