[[redirects]]
  from = "/login"
  to = "https://dispatchitt.onrender.com/login"
  status = 200

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/logged-in"
  to = "https://dispatchitt.onrender.com/logged-in"
  status = 200

[[redirects]]
  from = "/users"
  to = "https://dispatchitt.onrender.com/users"
  status = 200

[[redirects]]
  from = "/logout"
  to = "https://dispatchitt.onrender.com/logout"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
